config/routes.rb
class DomainConstraint
  def initialize(domain)
    @domains = [domain].flatten
  end
  
  def matches?(request)
    @domains.include? request.host
  end
end

Rails.application.routes.draw do
  root "application#index"

  constraints DomainConstraint.new('perf.vnetwork.vn') do
    get "/dashboard", to: "agent#index"
    resources :campaigns
    resources :sources
  end

  get '/uid/:id', to: "application#export"
  get '/uid/:id/callback', to: "application#callback"

  # Handling Err
  match '*path' => 'application#errors', via: :all
end

app/models/source.rb
class Source
  include Mongoid::Document
  field :name, type: String
  field :body, type: String
  field :size, type: Integer
  field :zone, type: Integer
  field :cost, type: Float
  field :target, type: String
  field :schedule_start, type: String
  field :schedule_end, type: String
  field :count, type: Integer
  field :updated_at, type: DateTime

  after_save :clear_cache
  after_destroy :clear_cache
  
  private
	  def clear_cache
	    $redis.del "sources"
	  end
end

app/controllers/sources_controller.rb
class SourcesController < AgentController
  def index
    @sources = JSON.parse Source.all.to_json

    Source.all.each do |source|
      source.update!(count: 0, updated_at: Time.now) if (Time.now.utc.to_datetime - source.updated_at).to_f > 1
    end
  end

  def new
    @source = Source.new
  end
  
  def edit
    if Source.find(id: params[:id]).nil?
      return redirect_to sources_path
    end

    @source = Source.find(id: params[:id])
  end

  def create
    if params[:source][:name].nil? || params[:source][:body].nil?
      return render json: { "message" => "Required can't be empty" }
    end

    if Source.create!(
      name: params[:source][:name],
      body: params[:source][:body].gsub(/[\r\n]+/,'').gsub('"',"'"),
      size: params[:source][:size],
      zone: params[:source][:size],
      cost: params[:source][:cost],
      target: params[:source][:target],
      schedule_start: (params[:source][:schedule].split(" - ").first.to_date) == (params[:source][:schedule].split(" - ").last.to_date) ? "" : params[:source][:schedule].split(" - ").first, 
      schedule_end: (params[:source][:schedule].split(" - ").first.to_date) == (params[:source][:schedule].split(" - ").last.to_date) ? "" : params[:source][:schedule].split(" - ").last,
      updated_at: Time.now
    )
      redirect_to sources_path
    end
  end

  def update
    if Source.find(id: params[:id]).nil?
      return redirect_to sources_path
    end
    
    @source = Source.find(id: params[:id])

    if @source.update!(
      name: params[:source][:name],
      body: params[:source][:body].gsub(/[\r\n]+/,'').gsub('"',"'"),
      size: params[:source][:size],
      zone: params[:source][:size],
      cost: params[:source][:cost],
      target: params[:source][:target],
      schedule_start: (params[:source][:schedule].split(" - ").first.to_date) == (params[:source][:schedule].split(" - ").last.to_date) ? "" : params[:source][:schedule].split(" - ").first, 
      schedule_end: (params[:source][:schedule].split(" - ").first.to_date) == (params[:source][:schedule].split(" - ").last.to_date) ? "" : params[:source][:schedule].split(" - ").last,
      updated_at: Time.now
    )
      redirect_to sources_path
    end
  end

  def destroy
    if Source.find(id: params[:id]).destroy
      redirect_to sources_path
    end
  end
end

app/views/sources/_form.html.erb
<div class="col-md-8 col-12">
  <div class="rounded bg-light core shadow">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active py-3 px-4 d-flex" id="general-tab" data-toggle="tab" href="#general" role="tab" aria-controls="general" aria-selected="true"><span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="19.454" height="20" viewBox="0 0 19.454 20"><path id="ic_settings_24px" d="M19.43,12.98A7.793,7.793,0,0,0,19.5,12a7.793,7.793,0,0,0-.07-.98l2.11-1.65a.5.5,0,0,0,.12-.64l-2-3.46a.5.5,0,0,0-.61-.22l-2.49,1a7.306,7.306,0,0,0-1.69-.98l-.38-2.65A.488.488,0,0,0,14,2H10a.488.488,0,0,0-.49.42L9.13,5.07a7.683,7.683,0,0,0-1.69.98l-2.49-1a.488.488,0,0,0-.61.22l-2,3.46a.493.493,0,0,0,.12.64l2.11,1.65A7.931,7.931,0,0,0,4.5,12a7.931,7.931,0,0,0,.07.98L2.46,14.63a.5.5,0,0,0-.12.64l2,3.46a.5.5,0,0,0,.61.22l2.49-1a7.306,7.306,0,0,0,1.69.98l.38,2.65A.488.488,0,0,0,10,22h4a.488.488,0,0,0,.49-.42l.38-2.65a7.683,7.683,0,0,0,1.69-.98l2.49,1a.488.488,0,0,0,.61-.22l2-3.46a.5.5,0,0,0-.12-.64ZM12,15.5A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z" transform="translate(-2.271 -2)" fill="#333333"/></svg></span><span class="my-auto">General</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link py-3 px-4 d-flex" id="target-tab" data-toggle="tab" href="#target" role="tab" aria-controls="target" aria-selected="false"><span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22"><path id="ic_gps_fixed_24px" d="M12,8a4,4,0,1,0,4,4A4,4,0,0,0,12,8Zm8.94,3A8.994,8.994,0,0,0,13,3.06V1H11V3.06A8.994,8.994,0,0,0,3.06,11H1v2H3.06A8.994,8.994,0,0,0,11,20.94V23h2V20.94A8.994,8.994,0,0,0,20.94,13H23V11H20.94ZM12,19a7,7,0,1,1,7-7A6.995,6.995,0,0,1,12,19Z" transform="translate(-1 -1)" fill="#333333"/></svg></span><span class="my-auto">Target</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link py-3 px-4 d-flex" id="scheduling-tab" data-toggle="tab" href="#scheduling" role="tab" aria-controls="scheduling" aria-selected="false"><span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20.14" viewBox="0 0 20 20.14"><path id="ic_access_alarm_24px" d="M22,5.72,17.4,1.86,16.11,3.39l4.6,3.86ZM7.88,3.39,6.6,1.86,2,5.71,3.29,7.24,7.88,3.39ZM12.5,8H11v6l4.75,2.85.75-1.23-4-2.37ZM12,4a9,9,0,1,0,9,9A9,9,0,0,0,12,4Zm0,16a7,7,0,1,1,7-7A6.995,6.995,0,0,1,12,20Z" transform="translate(-2 -1.86)" fill="#333333"/></svg></span><span class="my-auto">Scheduling</span></a>
      </li>
    </ul>
    <div class="p-4">
      <%= form_for [@source], html: { id: 'form', multipart: true } do |f| %>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
          <div class="row mb-3">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :name, 'Ads name *', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.text_field :name, placeholder: 'Ads source name', class: 'form-control', :required => true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :body, 'Third-party script *', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.text_area :body, size: '50x4', placeholder: 'Enter third-party script', class: 'form-control', :required => true %>
              </div>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :size, 'Ad size', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.select :size, options_for_select([["300x250", "1"], ["728x90", "2"], ["160x600", "3"], ["300x600", "4"], ["320x50", "5"], ["970x90", "6"], ["120x600", "7"]], selected: @source.size), {}, { class: "form-control" } %>
              </div>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :zone, 'Ad zone', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.select :zone, options_for_select([["Top", "1"], ["Bottom", "2"], ["Left", "3"], ["Right", "4"], ["Center", "5"]], selected: @source.zone), {}, { class: "form-control" } %>
              </div>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :cost, 'Cost *', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="input-group">
                <div class="input-group-prepend">
                  <div class="input-group-text">@</div>
                </div>
                <%= f.text_field :cost, class: 'form-control', :required => true %>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="target" role="tabpanel" aria-labelledby="target-tab">
          <div class="row">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :target, 'Target', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.text_field :target, placeholder: 'Set domain or IP', class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-9 offset-md-3 col-12">
              <small class="small text-muted">Domain does'nt need protocol. e.g: vnetwork.vn</small>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="scheduling" role="tabpanel" aria-labelledby="scheduling-tab">
          <div class="row">
            <div class="col-md-3 col-12 d-flex">
              <label class="form-label my-auto small" for="source_schedule">Scheduling Date</label>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <input placeholder="Click to pick date range for this ad" class="form-control" type="text" name="source[schedule]" value="<%= "#{ @source.schedule_start != "" ? @source.schedule_start : Date.today.strftime("%d/%m/%Y") } - #{ @source.schedule_end != "" ? @source.schedule_end : Date.today.strftime("%d/%m/%Y")  }" if action_name == "edit" %>" id="source_schedule">
              </div>
            </div>
            <div class="col-md-9 offset-md-3 col-12">
              <small class="small text-muted">Date format with DD/MM/YYYY. e.g: 20/11/1993</small>
            </div>
          </div>
        </div>
      </div>
      <div class="border-top mx-n4 mt-4 px-4 pt-4">
        <div class="d-flex justify-content-end">
          <a href="<%= url_for(:back) %>" class="btn btn-default silver mr-2">Quay Lại</a>
          <%= button_tag(type: "submit", class: "btn btn-default black", id: "submit") do %>
            <%= action_name == "edit" ? "Save" : "Create" %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sources/edit.html.erb
<div class="container-fluid py-5 bg-silver">
  <div class="row mx-0">
    <div class="col-12 mb-3">
      <div class="d-flex justify-content-between">
        <h5>Edit Ads Source :: <%= params[:id] %></h5>
      </div>
    </div>
    <%= render 'form' %>
    <div class="col-md-4 col-12">
      <div class="rounded shadow bg-light core p-4">
        _summary or anything
      </div>
    </div>
  </div>
</div>

app/views/sources/index.html.erb
<div class="container-fluid py-5 bg-silver">
  <div class="row mx-0">
    <div class="col-12 mb-4">
      <div class="d-flex justify-content-between">
        <h5 class="my-auto">Ads Sources</h5>
        <a href="<%= new_source_path %>" class="btn btn-default black my-auto">+ Create New Ads</a>
      </div>
    </div>
    <div class="col-12">
      <div class="rounded bg-light core shadow py-4 px-3">
        <table class="table croped mb-0">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Source Name</th>
              <th scope="col" class="text-center">Cost</th>
              <th scope="col" class="text-center">Target</th>
              <th scope="col" class="text-center">Date</th>
              <th scope="col" class="text-center">Display</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @sources.each do |source| %>
            <tr>
              <th scope="row"><%= source["_id"]["$oid"] %></th>
              <td><%= source["name"] %></td>
              <td class="text-center"><%= source["cost"] %></td>
              <td class="text-center"><%= source["target"].present? ? source["target"] : "-" %></td>
              <td class="text-center"><%= source["schedule_start"].to_date.strftime("%B %d, %Y") if source["schedule_start"].present? %> - <%= source["schedule_end"].to_date.strftime("%B %d, %Y") if source["schedule_end"].present? %></td>
              <td class="text-center"><%= source["count"].to_i %></td>
              <td>
                <div class="btn-group">
                  <a href="<%= edit_source_path(source["_id"]["$oid"]) %>" class="btn btn-default gray outline py-3 px-4 active"><span class="black">Edit</span></a>
                  <a href="<%= source_path(source["_id"]["$oid"]) %>" data-method="delete" data-confirm="Are you sure?" rel="nofollow" class="btn btn-default gray outline py-3 px-4 active"><span class="black">Delete Ads</span></a>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div

app/views/sources/new.html.erb
<div class="container-fluid py-5 bg-silver">
  <div class="row mx-0">
    <div class="col-12 mb-3">
      <div class="d-flex justify-content-between">
        <h5>New Ads Source</h5>
      </div>
    </div>
    <%= render 'form' %>
    <div class="col-md-4 col-12">
      <div class="rounded bg-light core shadow p-4">
        _summary or anything
      </div>
    </div>
  </div>
</div>