config/routes.rb
class DomainConstraint
  def initialize(domain)
    @domains = [domain].flatten
  end
  
  def matches?(request)
    @domains.include? request.host
  end
end

Rails.application.routes.draw do
  root "application#index"

  constraints DomainConstraint.new('perf.vnetwork.vn') do
    get "/dashboard", to: "agent#index"
    resources :campaigns
    resources :sources
  end

  get '/uid/:id', to: "application#export"
  get '/uid/:id/callback', to: "application#callback"

  # Handling Err
  match '*path' => 'application#errors', via: :all
end

app/models/campaign.rb
class Campaign
  include Mongoid::Document
  field :name, type: String
  field :model, type: Integer
  field :size, type: Integer
  field :zone, type: Integer
  field :target, type: String
  field :ads, type: String

  after_save :clear_cache
  after_destroy :clear_cache
  
  private
	  def clear_cache
	    $redis.del "campaigns"
	  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < AgentController
  def index
    @campaigns = JSON.parse Campaign.all.to_json
  end

  def new
    @campaign = Campaign.new
  end

  def edit
    if Campaign.find(id: params[:id]).nil?
      return redirect_to campaigns_path
    end
    
    @campaign = Campaign.find(id: params[:id])
    @sources = JSON.parse Source.all.to_json
  end

  def create
    if params[:campaign][:name].nil?
      return render json: { "message" => "Source name can't be empty." }
    end

    if Campaign.create!(
      name: params[:campaign][:name],
      model: params[:campaign][:model],
      size: params[:campaign][:size],
      zone: params[:campaign][:size],
      target: params[:campaign][:target],
      ads: params[:campaign][:ads]
    )
      redirect_to campaigns_path
    end
  end

  def update
    if Campaign.find(id: params[:id]).nil?
      return redirect_to campaigns_path
    end
    
    @campaign = Campaign.find(id: params[:id])

    if @campaign.update!(
      name: params[:campaign][:name],
      model: params[:campaign][:model],
      size: params[:campaign][:size],
      zone: params[:campaign][:size],
      target: params[:campaign][:target],
      ads: params[:campaign][:ads]
    )
      redirect_to campaigns_path
    end
  end
end

app/views/campaigns/_form.html.erb
<div class="col-md-8 col-12">
  <div class="rounded bg-light core shadow">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active py-3 px-4 d-flex" id="general-tab" data-toggle="tab" href="#general" role="tab" aria-controls="general" aria-selected="true"><span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="19.454" height="20" viewBox="0 0 19.454 20"><path id="ic_settings_24px" d="M19.43,12.98A7.793,7.793,0,0,0,19.5,12a7.793,7.793,0,0,0-.07-.98l2.11-1.65a.5.5,0,0,0,.12-.64l-2-3.46a.5.5,0,0,0-.61-.22l-2.49,1a7.306,7.306,0,0,0-1.69-.98l-.38-2.65A.488.488,0,0,0,14,2H10a.488.488,0,0,0-.49.42L9.13,5.07a7.683,7.683,0,0,0-1.69.98l-2.49-1a.488.488,0,0,0-.61.22l-2,3.46a.493.493,0,0,0,.12.64l2.11,1.65A7.931,7.931,0,0,0,4.5,12a7.931,7.931,0,0,0,.07.98L2.46,14.63a.5.5,0,0,0-.12.64l2,3.46a.5.5,0,0,0,.61.22l2.49-1a7.306,7.306,0,0,0,1.69.98l.38,2.65A.488.488,0,0,0,10,22h4a.488.488,0,0,0,.49-.42l.38-2.65a7.683,7.683,0,0,0,1.69-.98l2.49,1a.488.488,0,0,0,.61-.22l2-3.46a.5.5,0,0,0-.12-.64ZM12,15.5A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z" transform="translate(-2.271 -2)" fill="#333333"/></svg></span><span class="my-auto">General</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link py-3 px-4 d-flex" id="target-tab" data-toggle="tab" href="#target" role="tab" aria-controls="target" aria-selected="false"><span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22"><path id="ic_gps_fixed_24px" d="M12,8a4,4,0,1,0,4,4A4,4,0,0,0,12,8Zm8.94,3A8.994,8.994,0,0,0,13,3.06V1H11V3.06A8.994,8.994,0,0,0,3.06,11H1v2H3.06A8.994,8.994,0,0,0,11,20.94V23h2V20.94A8.994,8.994,0,0,0,20.94,13H23V11H20.94ZM12,19a7,7,0,1,1,7-7A6.995,6.995,0,0,1,12,19Z" transform="translate(-1 -1)" fill="#333333"/></svg></span><span class="my-auto">Target</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link py-3 px-4 d-flex" id="ads-tab" data-toggle="tab" href="#ads" role="tab" aria-controls="ads" aria-selected="false"><span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="16" viewBox="0 0 24 16"><path id="ic_devices_24px" d="M4,6H22V4H4A2.006,2.006,0,0,0,2,6V17H0v3H14V17H4ZM23,8H17a1,1,0,0,0-1,1V19a1,1,0,0,0,1,1h6a1,1,0,0,0,1-1V9A1,1,0,0,0,23,8Zm-1,9H18V10h4Z" transform="translate(0 -4)" fill="#333333"/></svg></span><span class="my-auto">Ads</span></a>
      </li>
    </ul>
    <div class="p-4">
      <%= form_for [@campaign], html: { id: 'form', multipart: true } do |f| %>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
          <div class="row">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :name, 'Campaign Name *', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group">
                <%= f.text_field :name, placeholder: 'Campaign name', class: 'form-control', :required => true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :model, 'Advertising Model', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.select :model, options_for_select([["CPM", "1"], ["CPC", "2"]], selected: @campaign.model), {}, { class: "form-control" } %>
              </div>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :size, 'Advertising size', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.select :size, options_for_select([["300x250", "1"], ["728x90", "2"], ["160x600", "3"], ["300x600", "4"], ["320x50", "5"], ["970x90", "6"], ["120x600", "7"]], selected: @campaign.size), {}, { class: "form-control" } %>
              </div>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :zone, 'Advertising zone', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.select :zone, options_for_select([["Top", "1"], ["Bottom", "2"], ["Left", "3"], ["Right", "4"], ["Center", "5"]], selected: @campaign.zone), {}, { class: "form-control" } %>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="target" role="tabpanel" aria-labelledby="target-tab">
          <div class="row">
            <div class="col-md-3 col-12 d-flex">
              <%= f.label :target, 'Target', class: 'form-label my-auto small' %>
            </div>
            <div class="col-md-9 col-12">
              <div class="form-group mb-0">
                <%= f.text_field :target, placeholder: 'Set domain or IP', class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-9 offset-md-3 col-12">
              <small class="small text-muted">Domain does'nt need protocol. e.g: vnetwork.vn</small>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="ads" role="tabpanel" aria-labelledby="ads-tab">
          <% if action_name == "edit" %>
            <div class="row">
              <div class="col-md-3 col-12 d-flex">
                <%= f.label :ads, 'Select Ads source *', class: 'form-label my-auto small' %>
              </div>
              <div class="col-md-9 col-12">
                <div class="form-group _assign mb-0">
                  <%= f.hidden_field :ads, id: "ads_selected" %>
                  <select class="custom-select navigation-slug" id="ads_list" multiple="multiple">
                    <% Source.where(size: @campaign["size"], zone: @campaign["zone"]).each do |source| %>
                      <option value="<%= source["id"] %>" <% if (@campaign["ads"].present?) && (@campaign["ads"].split(',').include? JSON.parse(source.to_json)["_id"]["$oid"]) %>selected="selected"<% end %>><%= source["name"] %></option>
                    <% end %>
                  </select>
                </div>
              </div>
            </div>
          <% else %>
            <div class="alert alert-warning p-3 font-weight-light d-flex">
              <span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path id="ic_error_24px" d="M12,2A10,10,0,1,0,22,12,10,10,0,0,0,12,2Zm1,15H11V15h2Zm0-4H11V7h2Z" transform="translate(-2 -2)" fill="var(--warning)"/></svg></span>
              <span class="my-auto">Please save new campaign before manage Ad sources</span>
            </div>
          <% end %>
        </div>
      </div>
      <div class="border-top mx-n4 mt-4 px-4 pt-4">
        <div class="d-flex justify-content-end">
          <a href="<%= url_for(:back) %>" class="btn btn-default silver mr-2">Quay Lại</a>
          <%= button_tag(type: "submit", class: "btn btn-default black", id: "submit") do %>
            <%= action_name == "edit" ? "Save" : "Create" %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/campaigns/edit.html.erb
<div class="container-fluid py-5 bg-silver">
  <div class="row mx-0">
    <div class="col-12 mb-3">
      <div class="d-flex justify-content-between">
        <h5>Edit Campaign :: <%= params[:id] %></h5>
      </div>
    </div>
    <%= render 'form' %>
    <div class="col-md-4 col-12">
      <div class="rounded shadow bg-light core p-4">
        _summary or anything
      </div>
    </div>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="container-fluid py-5 bg-silver">
  <div class="row mx-0">
    <div class="col-12 mb-4">
      <div class="d-flex justify-content-between">
        <h5 class="my-auto">Campaigns</h5>
        <a href="<%= new_campaign_path %>" class="btn btn-default black my-auto">+ Create New Campaign</a>
      </div>
    </div>
    <div class="col-12">
      <div class="rounded bg-light core shadow py-4 px-3">
        <table class="table croped mb-0">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Campaign Name</th>
              <th scope="col" class="text-center">Model</th>
              <th scope="col" class="text-center">Zone</th>
              <th scope="col" class="text-center">Size</th>
              <th scope="col" class="text-center">Target</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @campaigns.each do |campaign| %>
            <tr>
              <th><%= campaign["_id"]["$oid"] %></th>
              <td><%= campaign["name"] %></td>
              <td class="text-center"><%= campaignModel(campaign["model"]) %></td>
              <td class="text-center"><%= campaignZone(campaign["zone"]) %></td>
              <td class="text-center"><%= campaignSize(campaign["size"]) %></td>
              <td class="text-center"><%= campaign["target"].present? ? campaign["target"] : "-" %></td>
              <td>
                <div class="btn-group">
                  <a href="<%= edit_campaign_path(campaign["_id"]["$oid"]) %>" class="btn btn-default gray outline py-3 px-4 active"><span class="black">Edit</span></a>
                  <button type="button" class="btn btn-default gray outline" data-toggle="modal" data-target="#getCodeModal" data-campaign="<%= campaign["_id"]["$oid"] %>" data-script="<%= "<script src=\"https://adstrue.vncdn.vn/uid/#{campaign["_id"]["$oid"]}.js\"><script>" %>"><span class="my-auto mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="12" viewBox="0 0 20 12"><path id="ic_code_24px" d="M9.4,16.6,4.8,12,9.4,7.4,8,6,2,12l6,6Zm5.2,0L19.2,12,14.6,7.4,16,6l6,6-6,6-1.4-1.4Z" transform="translate(-2 -6)" fill="#333333"/></svg></span><span class="my-auto black">Get Code</span></button>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="getCodeModal" tabindex="-1" role="dialog" aria-labelledby="getCodeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="getCodeModalLabel">Get Code</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Embed:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
$("#getCodeModal").on("show.bs.modal", function (e) {
  var button = $(e.relatedTarget)
  var campaign = button.data('campaign')
  var script = button.data('script')
  var modal = $(this)

  modal.find('.modal-title').text('Campaign :: ' + campaign)
  modal.find('.modal-body textarea').val(script)
})
</script>

app/views/campaigns/new.html.erb
<div class="container-fluid py-5 bg-silver">
  <div class="row mx-0">
    <div class="col-12 mb-3">
      <div class="d-flex justify-content-between">
        <h5>New Campaign</h5>
      </div>
    </div>
    <%= render 'form' %>
    <div class="col-md-4 col-12">
      <div class="rounded bg-light core shadow p-4">
        _summary or anything
      </div>
    </div>
  </div>
</div>