config/routes.rb
class DomainConstraint
  def initialize(domain)
    @domains = [domain].flatten
  end
  
  def matches?(request)
    @domains.include? request.host
  end
end

Rails.application.routes.draw do
  root "application#index"

  constraints DomainConstraint.new('perf.vnetwork.vn') do
    get "/dashboard", to: "agent#index"
    resources :campaigns
    resources :sources
  end

  get '/uid/:id', to: "application#export"
  get '/uid/:id/callback', to: "application#callback"

  # Handling Err
  match '*path' => 'application#errors', via: :all
end

app/views/layouts/agent.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adstrue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
  </head>

  <body>
    <div class="main__heading position-relative">
      <nav class="container-fluid main__nav position-absolute">
        <div class="main__nav-list py-3 d-flex">
          <a href="<%= dashboard_path %>" class="btn btn-default dark main__nav-list--item my-auto mx-2 <%= current_page?(dashboard_path) ? "active" : "" %>">Dashboard</a>
          <a href="<%= campaigns_path %>" class="btn btn-default dark main__nav-list--item my-auto mx-2 <%= current_page?(campaigns_path) || controller_name == "campaigns" && action_name == "new" || controller_name == "campaigns" && action_name == "edit" ? "active" : "" %>">Campaigns</a>
          <a href="<%= sources_path %>" class="btn btn-default dark main__nav-list--item my-auto mx-2 <%= current_page?(sources_path) || controller_name == "sources" && action_name == "new" || controller_name == "sources" && action_name == "edit" ? "active" : "" %>">Manage Ads</a>
        </div>
      </nav>
    </div>
    <%= yield %>
  </body>

  <script type="text/javascript">
    $('input[name="source[schedule]"]').daterangepicker({
      locale: {
        format: 'DD/MM/YYYY'
      }
    });
    
    $('#submit').click(function () {
      $(':required:invalid', '#form').each(function () {
          var id = $('.tab-pane').find(':required:invalid').closest('.tab-pane').attr('id');

          $('.nav a[href="#' + id + '"]').tab('show');
      });
    });

    $("#ads_list").change(function(){
      $("#ads_selected").val($(this).val());
    })

    $(".navigation-slug").select2({
      placeholder: 'Select Ads',
      theme: 'bootstrap4',
      tags: true
    });
  </script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mongodb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>